# Generated by Django 5.0.6 on 2025-06-15 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(auto_now_add=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('nitrate', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('nitrite', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('ammonia', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('gh', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('kh', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '飼育ログ',
                'verbose_name_plural': '飼育ログ',
                'ordering': ['-log_date', '-id'],
            },
        ),
    ]
