# Generated by Django 5.0.6 on 2025-06-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_logentry_fish_type_logentry_tank_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='ammonia',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='gh',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='kh',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='nitrate',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='nitrite',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='ph',
        ),
        migrations.AddField(
            model_name='logentry',
            name='water_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='tank_type',
            field=models.CharField(choices=[('freshwater', '淡水'), ('saltwater', '海水')], default='freshwater', max_length=20),
        ),
    ]
